services:
  database:
    image: mysql:8.0
    container_name: cv_database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: cv_db
      MYSQL_USER: cv_user
      MYSQL_PASSWORD: cv_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - cv_network

  backend:
    image: ${DOCKERHUB_USER:-tu_usuario}/valdez-backend:v1
    build:
      context: ./backend
    container_name: cv_backend
    restart: always
    environment:
      PORT: 4000
      DB_HOST: database
      DB_PORT: 3306
      DB_USER: cv_user
      DB_PASSWORD: cv_password
      DB_DATABASE: cv_db
    ports:
      - "4000:4000"
    depends_on:
      - database
    networks:
      - cv_network

  frontend:
    image: ${DOCKERHUB_USER:-tu_usuario}/valdez-frontend:v1
    build:
      context: ./frontend
    container_name: cv_frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - cv_network

volumes:
  mysql_data:

networks:
  cv_network:
    driver: bridge
